# Generated by Django 2.1.5 on 2019-02-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('street_addr', models.CharField(default='', max_length=100)),
                ('zip', models.CharField(default='', max_length=5)),
                ('max_capacity', models.IntegerField(default=10)),
                ('current_capacity', models.IntegerField(default=0)),
                ('photo', models.URLField(default='')),
                ('owner', models.CharField(default='', max_length=50)),
                ('location', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shelterme.Location')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='shelter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shelterme.Shelter'),
        ),
    ]
